version: '3'
services:
  iris:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: iris
    ports:
     - "52773:52773"
     - "51773:51773"
    volumes:
     - .:/external

networks:
  default:
    ipam:
      config:
        - subnet: 172.177.0.0/16
